peps/peps/urls.py
from django.contrib import admin
from django.urls import path
#instaladas por mi
from . import views 
from django.urls import include
from users.views import UsersListView,UserUdpateView,UserUdpateClave,UserDelete,CambiarClave



urlpatterns = [
    path('admin/', admin.site.urls),
    #instaladas por mi
    path('',views.index, name='index'),
    path('usuarios/registro',views.register, name='register'),
    path('usuarios/login',views.login_view, name='login'),
    path('usuarios/logout',views.logout_view, name='logout'),
    path('usuarios/list',UsersListView.as_view(), name='listarUsuarios'),
    path('usuarios/editar', UserUdpateView, name='updateusuarios'),
    path('usuarios/editarClave', UserUdpateClave, name='updateusuariosClave'),
    path('usuarios/eliminarUsuarios', UserDelete, name='deleteusuarios'),
    path('usuarios/cambiarClave', CambiarClave, name='CambiarClave'),
    path('persona/', include('personas.urls')),
]

peps/users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass
    #is_admin = models.CharField(max_length=4)

peps/templates/usuarios/cambiarClave.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/register.css' %}">

<div class="col">
  {% include 'messages.html' %}
  <h2>Cambiar contraseña</h2>
  <!-- Formulario -->
  <form class="form-create" method="post">
      {% csrf_token %}
    
    <!-- Mostar el formulario de una manera mas rapida-->
    {% for field in form %}
    <div class="form-group">

      {{ field.label_tag }}
      {{ field }}
    
      {% if field.errors %}
      {{ field.errors }}
      {% endif %}

    </div>
  {% endfor %}
  <button type="submit" class="btn btn-success" style="background-color:rgb(4,105,4);">Guardar</button>
  
  </form>
  
</div>

{% endblock %}

peps/templates/usuarios/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}




{% if user.is_superuser == 1 %} <!-- valido que el usuario que ingresa a esta ruta sea un administrador tipo= 1-->


<h3>{{ message }}</h3>

<div class="container">  <!-- div inicial-->
  <div class="card shadow table-responsive">
      <div class="card-body table-responsive">
          <!-- Tabla -->
          <table class="table table-bordered table-hover"> <!-- table-striped-->
            <!-- columnas de la tabla table-light thead-light table-secondary-->
              <thead class="table-secondary">
                  <tr>
                      <th scope="col">Id</th>
                      <th scope="col">Usuario</th>
                      <th scope="col">Email</th>
                      <th scope="col">Tipo de usuario</th>
                      <th scope="col">Fecha y hora de creacion</th>
                      <th scope="col">Editar</th>
                      <th scope="col">Clave</th>
                      <th scope="col">Borrar</th>
                  </tr>
              </thead>
          <!-- columnas de la tabla-->
          <tbody>
            <!-- inicio for -->
              {% for usuarios in user_list %}
                  <tr>
                      <td>{{ usuarios.id }}</td> <!-- id-->
                      <td>{{ usuarios.username }}</td> <!--username-->
                      <td>{{ usuarios.email }}</td> <!-- email-->
                      <!-- valido si el tipo de usuario es 1 me muestre administrador sino cliente-->
                      {% if usuarios.is_superuser == 1 %}
                      <td>Administrador</td>
                      {% else %}
                      <td>Cliente</td>
                      {% endif %}
                      <td>{{ usuarios.date_joined }}</td> <!-- fecha y hora de creacion-->
                      <td><a href="" class="btn btn-info fa-solid fa-pen-to-square" id="btn-edit{{ usuarios.id }}" data-toggle="modal" data-target="#modal{{ usuarios.id }}"></a></td>
                      <td><a href="" class="btn btn-success fa-solid fa-calendar-check" id="btn-cambiar{{ usuarios.id }}" data-toggle="modal" data-target="#modal2{{ usuarios.id }}"></a></td>
                      <td><a href="" class="btn btn-danger fa-solid fa-trash-can" id="btn-eliminar{{ usuarios.id }}" data-toggle="modal" data-target="#modal3{{ usuarios.id }}"></a></td>
                     
                  </tr>

                  {% include 'usuarios/modalEditar.html' %}
                  {% include 'usuarios/modalClave.html' %}
                  {% include 'usuarios/modalEliminar.html' %}

              {% endfor %}
              <!-- Final for -->
          </tbody>

      </table>

      {% include 'usuarios/snippets/paginator.html' %}    <!--  Dentro de este archivo configuro las paginas -->

<!-- final Tabla -->
      </div>
  </div>
</div>  <!-- div final-->

{% else %}  <!-- aqui pongo el final del condicional para saber si el que accede es un administrador-->

{% include 'accesoRestringido.html' %}    <!--  Dentro de este archivo configuro las paginas -->

{% endif %}  <!-- aqui pongo el final del condicional para saber si el que accede es un administrador-->

{% endblock %}

peps/templates/usuarios/listUsers.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="col">
    <div class="h2">{{ user.username }}</div>
    <div class="h5 font-weight-bold">
      Precio: <span class="text-danger">{{ user.email }}</span>
    </div>
    <div class="">
      <p>{{ user.is_superuser }}</p>
    </div>
    <div class="">
      
    </div>

  </div>

{% endblock %}

peps/templates/usuarios/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<link rel="stylesheet" href="{% static 'css/login.css' %}">


<div class="container mt-3">
    <!-- formulario-->
    <form class="form-signin" action="" method="post">
        {% csrf_token %}  <!--para que no genere error-->
        <img class="mb-4" src="{% static 'img/logoCootep.png' %}" alt="" width="300">
        <h1 class="h3 mb-3 font-weight-normal">Inicio de Sesi&oacute;n App</h1>
        
        <!--
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" class="form-control">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" class="form-control">
        </div>
        
-->
        
        {% for field in form %}
        <div class="form-group">
    
          {{ field.label_tag }}
          {{ field }}
        
          {% if field.errors %}
          {{ field.errors }}
          {% endif %}
    
        </div>
      {% endfor %}

        
        <button type="submit" style="background-color:rgb(4,105,4);" class="w-75 btn btn-lg btn-success" >Iniciar sesi&oacute;n</button>
        <br><br>
        <a class="" href="#">Recordar contraseña</a>
        <br>
        {% include 'messages.html' %}

        <footer>
            <br>
            <br>
            <div class="container">
                <div class="row">
                    <p class="CopyRight text-muted">All Copyright <span id="anio_actual"></span> &copy; COOTEP <br> Diseñado por Ing de sistemas Maicol Yela</p>
                </div>
            </div>
        </footer>  

    </form>
    <script src="{% static 'js/hora.js' %}"></script>
 </div>

{% endblock %}

peps/templates/usuarios/modalClave.html
<!-- modal cambiar contraseña-->

<div class="modal fade" id="modal2{{ usuarios.id }}">
  <div class="modal-dialog modal-dialog-centered">  <!--<div class="modal-dialog modal-dialog-centered">-->
    <div class="modal-content">
    
      <!-- Modal Header -->
      <div class="modal-header">
        <h3 class="modal-title">Cambiar Contraseña</h3>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      
      <!-- Modal body -->
      <div class="modal-body">
        <form action="{% url 'updateusuariosClave' %}" method="post">
          {% csrf_token %}

        <div id="miDiv" class="form-inline col-sm-12 mt-3" style="display: none;">
          <label class="control-label col-sm-4" for="id"><h5>id</h5></label>
          <input readonly minlength="4" type="text" class="form-control col-sm-7" name="id" value="{{ usuarios.id }}">
        </div>
        
        <div class="form-inline col-sm-12 mt-3">
          <label class="control-label col-sm-4" for="passnew" id="mi-label"><h5>Nueva contraseña</h5></label>
          <input minlength="4" type="password" class="form-control col-sm-7" name="passnew" required>
        </div>
        
      </div>
  
      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary btnEditar">Guardar cambios</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
      </div>

      </form>

    </div>
  </div>
</div>
<!-- cierre modal cambiar contraseña-->

peps/templates/usuarios/modalEditar.html
<!-- modal editar-->

<div class="modal fade" id="modal{{ usuarios.id }}"> 
  <div class="modal-dialog modal-dialog-centered">  <!--<div class="modal-dialog modal-dialog-centered">-->
    <div class="modal-content">
    
      <!-- Modal Header -->
      <div class="modal-header">
        <h3 class="modal-title">Editar usuarios</h3>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      
      <!-- Modal body -->
      <div class="modal-body">
        <form action="{% url 'updateusuarios' %}" method="post">
          {% csrf_token %}
          
        <div id="miDiv" class="form-inline col-sm-12 mt-3" style="display: none;">
            <label class="control-label col-sm-4" for="id"><h5>id</h5></label>
            <input readonly minlength="4" type="text" class="form-control col-sm-7" name="id" value="{{ usuarios.id }}">
        </div>

        <div class="form-inline col-sm-12 mt-3">
          <label class="control-label col-sm-4" for="UserName"><h5>Usuario</h5></label>
          <input readonly minlength="4" type="text" class="form-control col-sm-7" name="username" value="{{ usuarios.username }}">
        </div>
        <div class="form-inline col-sm-12 mt-3">
          <label class="control-label col-sm-4" for="UserEmail"><h5>Email</h5></label>
          <input id="idemail" minlength="6" type="email" class="form-control col-sm-7" name="userEmail" value="{{ usuarios.email }}" required>
        </div>
  
        <div class="form-inline col-sm-12 mt-3">
          <label class="control-label col-sm-4" for="tipoUsuario"><h5>Tipo usuario</h5></label>
          
          <select name="tipousuario" id="tipoUsuario" value="{{ usuarios.is_superuser }}" class="form-control col-sm-7">
            {% if usuarios.is_superuser == 1 %}
            <option value="1"selected>Administrador</option>
            <option value="0">Cliente</option>
            {% else %}
            <option value="1">Administrador</option>
            <option value="0"selected>Cliente</option>
            {% endif %}
          </select>
        </div>
        
      </div>
  
      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary btnEditar">Guardar cambios</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
      </div>

      </form>

    </div>
  </div>
</div>
<!-- cierre modal editar-->

peps/templates/usuarios/modalEliminar.html
<!-- modal eliminar Usuario-->

<div class="modal fade" id="modal3{{ usuarios.id }}"> 
    <div class="modal-dialog modal-dialog-centered">  <!--<div class="modal-dialog modal-dialog-centered">-->
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h3 class="modal-title">Eliminar Usuario</h3>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
          <form action="{% url 'deleteusuarios' %}" method="post">
            {% csrf_token %}

            <div id="miDiv" class="form-inline col-sm-12 mt-3" style="display: none;">
                <label class="control-label col-sm-4" for="id"><h5>id</h5></label>
                <input readonly minlength="4" type="text" class="form-control col-sm-7" name="id" value="{{ usuarios.id }}">
            </div>  
            
          <h5>¿Estás seguro en eliminar el usuario <b>{{ usuarios.username }} ?</b></h5>
          <h5>Recuerde que este proceso es irreversible.</h5>
        </div>
    
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary btnEditar">Eliminar</button>
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
        </div>

        </form>

      </div>
    </div>
  </div>
  <!-- cierre modal eliminar Usuario-->

peps/templates/usuarios/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if user.is_superuser == 1 %} <!-- valido que el usuario que ingresa a esta ruta sea un administrador tipo= 1-->

<link rel="stylesheet" href="{% static 'css/register.css' %}">

<div class="col">
  {% include 'messages.html' %}
  <h2>Crear usuario</h2>
  <!-- Formulario -->
  <form class="form-create" method="post">
      {% csrf_token %}
    
    <!-- Mostar el formulario de una manera mas rapida-->
    {% for field in form %}
    <div class="form-group">

      {{ field.label_tag }}
      {{ field }}
    
      {% if field.errors %}
      {{ field.errors }}
      {% endif %}

    </div>
  {% endfor %}
  <button type="submit" class="btn btn-success" style="background-color:rgb(4,105,4);">Guardar</button>
  
  </form>
  
</div>


{% else %}  <!-- aqui pongo el final del condicional para saber si el que accede es un administrador-->

{% include 'accesoRestringido.html' %}    <!--  Dentro de este archivo configuro el mensaje a mostar -->

{% endif %}  <!-- aqui pongo el final del condicional para saber si el que accede es un administrador-->

{% endblock %}